{% set name = "pydivert" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pydivert-{{ version }}.tar.gz
  sha256: 44c252beb00926b640a43c85effdd94bbfab6993b60814eba8644fa41ec625f6

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [not win]

requirements:
  host:
    - pip
    - setuptools
    - python
  run:
    - enum34 >=1.1.6  # [py==27 or py==33]
    - python
    - win_inet_pton >=1.0.1  # [py==27 or py==33]

test:
  imports:
    - pydivert
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ffalcinelli/pydivert
  summary: Python binding to windivert driver
  doc_url: https://pythonhosted.org/pydivert/
  license: LGPL-3.0-or-later
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jonashaag
    - AdrianFreundQC
    - freundTech
