{% set name = "pydivert" %}
{% set version = "3.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pydivert-{{ version }}.tar.gz
  sha256: 93ec09b012b80cfa43afe7c11f3cb9101369f78e1489f41ae37dda637449083c

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [not win]

requirements:
  host:
    - pip
    - hatchling
    - python
  run:
    - python

test:
  imports:
    - pydivert
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ffalcinelli/pydivert
  summary: Python binding to windivert driver
  doc_url: https://pythonhosted.org/pydivert/
  license: LGPL-3.0-or-later
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jonashaag
    - AdrianFreundQC
    - freundTech
