{% set name = "pydivert" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pydivert-{{ version }}.tar.gz
  sha256: f1fe65aba3ee2fc1533094df92abdea66a78749d52d6a29f089d580f90c22950

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [not win]

requirements:
  host:
    - pip
    - hatchling
    - python
  run:
    - python

test:
  imports:
    - pydivert
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ffalcinelli/pydivert
  summary: Python binding to windivert driver
  doc_url: https://pythonhosted.org/pydivert/
  license: LGPL-3.0-or-later
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jonashaag
    - AdrianFreundQC
    - freundTech
